version: '3.8'
services:
  postgres:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - /Users/maria/Desktop/docker/postgres:/home/node/app
    ports:
      - "5432:5432"