# Generated by Django 4.2 on 2024-03-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LottoAccount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lotto_id", models.CharField(max_length=255, verbose_name="로또 아이디")),
                (
                    "lotto_password",
                    models.CharField(max_length=255, verbose_name="로또 비밀번호"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lotto_account",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="본인인증용 email"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="로그인 아이디")),
                ("password", models.CharField(max_length=100, verbose_name="비밀번호")),
                ("phone", models.CharField(max_length=11, verbose_name="phone 번호")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["name", "password"], name="name_password_index"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email", "name"), name="unique_email"
            ),
        ),
        migrations.AddField(
            model_name="lottoaccount",
            name="user_id",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.user",
            ),
        ),
    ]
